import { Inter } from "next/font/google";
import "./globals.css";

const roboto = Inter({ subsets: ["latin"], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-[95%] mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
